name: test

on:
  workflow_dispatch: # manually run sync

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: test
              run: |
                python3 test.py
