name: test

on:
  workflow_dispatch: # manually run sync

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: test
              run: |
                echo "fgdfsg" >> a.txt
                echo "fgdfs3423g" >> b.txt
                echo "fg234g" >> c.txt

            - name: Release
              uses: dothq/tag-and-release-and-upload@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                version: "${{ github.sha }}"
                name: "${{ github.sha }}"
                assets: '[
                  "a.txt",
                  "b.txt",
                  "c.txt"
                ]'
                overwrite: true
